### PR TITLE
submit answers

### PR DESCRIPTION
**Pull request by williamwang96**

### CODE REVIEW

**Comment by mrcaron** [comment]
Thanks, @williamwang96 ! I'm a bit behind due to an overwhelming amount of work this week, but I'll be in touch next week as I review solutions and resumes.

**Comment by mrcaron** [comment]
Hi @williamwang96, could you send me your resume at Michael.Caron@3ds.com? Thanks!

**Comment by williamwang96** [comment]
It's done! Thanks @mrcaron for your time!

**Comment by mrcaron** [comment]
Hi William, please indicate interview times that work for you here: https://docs.google.com/document/d/1F2XUtdDo9_81fU2VzonBMpHtZvOnFCzX8oU0OGB9NW8/edit?usp=sharing.

**Comment by mrcaron** [comment]
Hi William, are you willing to meet at 1-2:30 tomorrow instead of 12:30 - 2:00 ?

**Comment by williamwang96** [comment]
Hello Mr. Caron, yes that time works for me. I'll see you at 1 then!

**Pull request closed without merging**
