### PR TITLE
MyAnswers_codes

### PR DESCRIPTION
**Pull request by jeeerice**
I wrote code in Java using recursive call to check is a given string is palindrome.

### CODE REVIEW

**Comment by mrcaron** [comment]
Thanks, @jeeerice ! I'm a bit behind due to an overwhelming amount of work this week, but I'll be in touch next week as I review solutions and resumes.

**Comment by mrcaron** [comment]
Hi @jeeerice, I'm setting up interview slots now, but I need to know what your full name and email address are :) Could you send that to me please?

**Comment by jeeerice** [comment]
Hi Michael,
My Full name is Zelin Hao and my email address is hao37@wisc.edu<mailto:hao37@wisc.edu>. Thanks for your reply!

Best,
Zelin Hao

On Mar 2, 2018, at 12:07 PM, Michael Caron <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jeeerice<https://github.com/jeeerice>, I'm setting up interview slots now, but I need to know what your full name and email address are :) Could you send that to me please?

**Comment by mrcaron** [comment]
Thanks Zelin! 

Please indicate on this sheet (https://docs.google.com/document/d/1F2XUtdDo9_81fU2VzonBMpHtZvOnFCzX8oU0OGB9NW8/edit?usp=sharing) interview times that work for you.

Cheers!

**Comment by jeeerice** [comment]
Dear Mr. Caron

I hope you are well! I am checking in on the software engineering internship role. It was great to meet you and the team earlier and I am looking forward to your update. Please let me know if there is anything else I can do to assist in the decision-making process.

Thank you!
Zelin Hao
E: zelinjerryhao@hotmail.com<mailto:zelinjerryhao@hotmail.com>


On Mar 5, 2018, at 10:10 PM, Michael Caron <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Zelin!

Please indicate on this sheet (https://docs.google.com/document/d/1F2XUtdDo9_81fU2VzonBMpHtZvOnFCzX8oU0OGB9NW8/edit?usp=sharing) interview times that work for you.

Cheers!

**Pull request closed without merging**
